#!/usr/bin/perl 

#    More, Ashwini    Account: jadrn031
#                     CS545, Fall 2016
#                     Project #4

            
print "content-type:text/html\n\n";
print "<html>";
print "<head>";
   print "<meta charset=\"utf-8\">";
   print "<meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />";
   print "<meta http-equiv=\"Pragma\" content=\"no-cache\" />";
   print "<meta http-equiv=\"Expires\" content=\"0\" />"; 
   print "<title>Bertha's Deluxe Chocolates-HomePage</title>";
    print "<link rel=\"stylesheet\" href=\"bootstyle.css\">";
     print "<link rel=\"stylesheet\" href=\"bootstyle-cart.css\">";
   print "<script src=\"/jquery/jquery.js\"></script>\n";
   print "<script src=\"/jquery/jQueryUI.js\"></script>\n";   
   
print "</head>\n";
print "<body>\n";

print "<form method=\"post\" name=\"myForm\" action=\"/perl/jadrn031/proj4/cookie.cgi\">\n";
print "<div class=\"panel-group\" id=\"accordion\">\n";
    print "<div class=\"panel panel-default\">\n";
      print "<div class=\"panel-heading\">\n";
        print "<h4 class=\"panel-title\">\n";
          print "<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse1\">1. ENTER EMAIL ADDRESS</a>\n";
        print "</h4>\n";
      print "</div>\n";
      print "<div id=\"collapse1\" class=\"panel-collapse collapse in\">\n";
        print "<div class=\"panel-body\">\n";
           print "<div class=\"form-group\">\n";
             print "<font color=\"red\">*</font><label for=\"email\">Email address:</label>\n";
	     print "<input type=\"email\" id=\"emailInput\" class=\"form-control\" required>\n";
           print "</div>\n";
        print "</div>\n";
      print "</div>\n";
    print "</div>\n";
    print "<div class=\"panel panel-default\">\n";
      print "<div class=\"panel-heading\">\n";
      print "  <h4 class=\"panel-title\">\n";
          print "<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse2\">2. DELIVERY ADDRESS</a>\n";
        print "</h4>\n";
      print "</div>\n";
      print "<div id=\"collapse2\" class=\"panel-collapse collapse in\">\n";
        print "<div class=\"panel-body\">\n";
           print "<div class=\"form-group\">\n";
           print " <table cellpadding=\"10\">\n";
           print " <tr>\n";
           print "  <td><font color=\"red\">*</font><label for=\"name\">Name:</label></td>\n";
           print "  <td><input type=\"text\" id=\"name\" required></td>\n";
           print " </tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"address\">Address Line 1:</label></td>\n";
             print "<td><input type=\"text\" id=\"address\" required></td>\n";
             print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"address\">Address Line 2:</label></td>\n";
             print "<td><input type=\"text\" id=\"landmark\" required></td>\n";
             print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"city\">City:</label></td>\n";
             print "<td><input type=\"text\" id=\"city\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
            print "<td><font color=\"red\">*</font><label for=\"state\">State:</label></td>\n";
             print "<td><input type=\"text\" id=\"state\" required></td>\n";
            print "</tr>\n";
             print "<tr>\n";
            print "<td><font color=\"red\">*</font><label for=\"pincode\">ZIP:</label></td>\n";
             print "<td><input type=\"text\" id=\"pin\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
            print "<td><font color=\"red\">*</font><label for=\"country\">Country:</label></td>\n";
             print "<td><input type=\"text\" id=\"country\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"phone\">Phone:</label></td>\n";
             print "<td><input type=\"tel\" id=\"phone\" Placeholder=\"xxx-xxx-xxxx\" required></td>\n";
            print "</tr></table></div>\n";
        print "</div>\n";
      print "</div>\n";
    print "</div>\n";
    print "<div class=\"panel panel-default\">\n";
    print "<div class=\"panel-heading\">\n";
        print "<h4 class=\"panel-title\">\n";
          print "<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse22\">3. BILLING ADDRESS</a>\n";
        print "</h4>\n";
      print "</div>\n";
      print "<div id=\"collapse22\" class=\"panel-collapse collapse in\">\n";
        print "<div class=\"panel-body\">\n";
             print "<div class=\"form-group\">\n";
             print "<div class=\"checkbox\">\n";
         	   print "<label><input type=\"checkbox\" id=\"chekbox\">Same as Delivery address?</label>\n";
             print "</div>\n";
            print "<table cellpadding=\"10\">\n";
            print "<tr>\n";      
             print "<td><font color=\"red\">*</font><label for=\"name\">Name:</label></td>\n";
             print "<td><input type=\"text\" id=\"name2\" name=\"name2\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"address\">Address Line 1:</label></td>\n";
             print "<td><input type=\"text\" id=\"address2\" required></td>\n";
             print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"address\">Address Line 2:</label></td>\n";
             print "<td><input type=\"text\" id=\"landmark2\" required></td>\n";
             print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"city\">City:</label></td>\n";
             print "<td><input type=\"text\" id=\"city2\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
            print "<td><font color=\"red\">*</font><label for=\"state\">State:</label></td>\n";
             print "<td><input type=\"text\" id=\"state2\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
            print "<td><font color=\"red\">*</font><label for=\"pincode\">ZIP:</label></td>\n";
             print "<td><input type=\"text\" id=\"pin2\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
            print "<td><font color=\"red\">*</font><label for=\"country\">Country:</label></td>\n";
             print "<td><input type=\"text\" id=\"country2\" required></td>\n";
            print "</tr>\n";
            print "<tr>\n";
             print "<td><font color=\"red\">*</font><label for=\"phone\">Phone:</label></td>\n";
             print "<td><input type=\"tel\" id=\"phone2\" Placeholder=\"xxx-xxx-xxxx\" required></td>\n";
            print "</tr></table>\n";
            print "</div>\n";
        print "</div>\n";
      print "</div>\n";
    print "</div>\n";

   print "<div class=\"panel panel-default\">\n";
      print "<div class=\"panel-heading\">\n";
        print "<h4 class=\"panel-title\">\n";
          print "<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse4\">4. MAKE PAYMENT</a>\n";
        print "</h4>\n";
      print "</div>\n";
      print "<div id=\"collapse4\" class=\"panel-collapse collapse in\">\n";
        print "<div class=\"panel-body\" style=\"text-align:center;\">\n";
          print "<h6 style=\"font-weight:bold;\">Credit Card Type\n";
          print "<form role=\"form\">\n";
             print "&nbsp;&nbsp;<input type=\"radio\" name=\"optradio\" checked>\n";
                 print "<img src=\"http://www.credit-card-logos.com/images/visa_credit-card-logos/visa_logo_3.gif\" width=\"35\" height=\"22\"/>\n";
             print "&nbsp;&nbsp;<input type=\"radio\" name=\"optradio\">\n";
                 print "<img src=\"http://www.credit-card-logos.com/images/mastercard_credit-card-logos/mastercard_logo_3.gif\" width=\"35\" height=\"22\"/>\n";
             print "&nbsp;&nbsp;<input type=\"radio\" name=\"optradio\">\n";
                 print "<img src=\"http://www.credit-card-logos.com/images/discover_credit-card-logos/discover_logo_3.gif\" width=\"35\" height=\"22\"/>\n";
          print "</form>\n";
          print "</h6>\n";
             print "<hr>\n";
              print "<div id=\"\" style=\"margin-left:90px;\">  \n";
             print "<pre><input type=\"text\" id=\"card\" name=\"card\" Placeholder=\"Card Number\" size=\"33px\">\n";
             print "<br>Expiry Date <input type=\"text\" id=\"expiry\"  Placeholder=\"MM/YY\" size=\"5px\">     <input type=\"text\" id=\"cvv\"  Placeholder=\"CVV\" size=\"5px\">\n";
             print "<br><input type=\"text\" id=\"name_card\"  Placeholder=\"Name on card\" size=\"33px\"></pre>\n";
             print "</div>\n";
       print "</div>\n";
      print "</div>\n";
      print "</div>\n";
      print "</div>\n";
    print "</div>\n";
print "<div id=\"btn_panel\"><button type=\"button\" class=\"cancel\">Cancel</button>\n";
print "<button type=\"submit\" class=\"continue\">Continue</button></div>\n";
print "<br>\n";
print "<label for \"message\" id=\"message\"></label>\n";
  print "</div> \n";

print "</form>\n";


print "</body>\n";
print "</html>\n";